[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kernelfunctions"
authors = [
    {name = "Chris Cummings", email = "chriscummings@nvidia.com"},
]
description = "Call compute kernel functions in SGL"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "sgl @ git+https://gitlab-master.nvidia.com/skallweit/sgl.git"
]
dynamic = ["version"]
